//! Beancount text exporter for [`LedgerSnapshot`].
//!
//! The output loads cleanly in `bean-check` (and therefore in
//! Fava). It preserves:
//!
//! * every account (one `open` directive at the ledger's first
//!   transaction date);
//! * every transaction as a `txn` block with one posting per
//!   leg;
//! * per-posting currency via commodity annotations
//!   (`<amount> CCY`);
//! * every commodity seen in the snapshot, so Fava does not
//!   warn about unknown currencies.
//!
//! The output is intentionally textual (no JSON round-trip).

use std::fmt::Write as _;

use chrono::NaiveDate;

use super::LedgerSnapshot;

/// Render the snapshot as a complete Beancount file.
pub fn render(snapshot: &LedgerSnapshot) -> String {
    let mut out = String::with_capacity(8 * 1024);
    let _ = writeln!(
        out,
        "; Generated by openaccounting {}",
        env!("CARGO_PKG_VERSION")
    );
    let _ = writeln!(
        out,
        "; Ledger: {} ({})",
        snapshot.ledger.name, snapshot.ledger.id
    );
    let _ = writeln!(
        out,
        "; Exported at {}",
        chrono::Utc::now().format("%Y-%m-%dT%H:%M:%SZ")
    );
    let _ = writeln!(out);
    let _ = writeln!(
        out,
        "option \"title\" \"{}\"",
        escape_beancount_string(&snapshot.ledger.name)
    );
    let _ = writeln!(
        out,
        "option \"operating_currency\" \"{}\"",
        snapshot.ledger.base_currency
    );
    // Declare every commodity seen in the ledger. Beancount
    // does not require this, but Fava surfaces a warning when a
    // commodity is used without a `commodity` directive.
    for cur in &snapshot.currencies {
        let _ = writeln!(out, "1970-01-01 commodity {}", cur);
    }
    let _ = writeln!(out);

    // Choose the open-date for each account: the earliest
    // transaction date that posts to it, falling back to the
    // ledger's created_at date. If neither is available, fall
    // back to today.
    let ledger_open_date = snapshot
        .transactions
        .iter()
        .map(|t| t.txn_date)
        .min()
        .unwrap_or_else(|| snapshot.ledger.created_at.date_naive());

    // Index postings by account so we can look up the first
    // use of each account.
    let mut first_use: std::collections::BTreeMap<uuid::Uuid, NaiveDate> =
        std::collections::BTreeMap::new();
    let txn_by_id: std::collections::HashMap<uuid::Uuid, &super::TransactionRow> =
        snapshot.transactions.iter().map(|t| (t.id, t)).collect();
    for p in &snapshot.postings {
        if let Some(t) = txn_by_id.get(&p.transaction_id) {
            let entry = first_use.entry(p.account_id).or_insert(t.txn_date);
            if t.txn_date < *entry {
                *entry = t.txn_date;
            }
        }
    }

    // Index account id -> name for leg rendering.
    let account_name: std::collections::HashMap<uuid::Uuid, String> = snapshot
        .accounts
        .iter()
        .map(|a| (a.id, beancount_account_name(&a.name)))
        .collect();

    // Emit accounts in a stable order: by type then by name.
    let mut account_order: Vec<&super::AccountRow> = snapshot.accounts.iter().collect();
    account_order.sort_by(|a, b| a.r#type.cmp(&b.r#type).then(a.name.cmp(&b.name)));

    for a in &account_order {
        let open_date = first_use.get(&a.id).copied().unwrap_or(ledger_open_date);
        let date = format_beancount_date(open_date);
        let name = account_name
            .get(&a.id)
            .map(String::as_str)
            .unwrap_or("Unknown");
        let _ = writeln!(out, "{} open {} {}", date, name, a.currency);
    }
    let _ = writeln!(out);

    // Emit transactions in date order.
    let mut txns = snapshot.transactions.iter().collect::<Vec<_>>();
    txns.sort_by(|a, b| {
        a.txn_date
            .cmp(&b.txn_date)
            .then(a.created_at.cmp(&b.created_at))
    });

    for t in txns {
        let date = format_beancount_date(t.txn_date);
        let payee = t
            .payee
            .as_deref()
            .filter(|s| !s.is_empty())
            .map(escape_beancount_string);
        let desc = escape_beancount_string(&t.description);
        let narration = match payee {
            Some(p) => format!("\"{}\" \"{}\"", p, desc),
            None => format!("\"{}\"", desc),
        };
        let _ = writeln!(out, "{} * {}", date, narration);
        for p in snapshot
            .postings
            .iter()
            .filter(|p| p.transaction_id == t.id)
        {
            let account_name = account_name
                .get(&p.account_id)
                .map(String::as_str)
                .unwrap_or("Unknown");
            // Beancount convention: debits are positive, credits
            // are negative. Our schema uses an explicit
            // `direction` column, so negate CREDIT legs.
            let signed = match p.direction.as_str() {
                "DEBIT" => p.amount,
                "CREDIT" => -p.amount,
                other => panic!("unexpected direction {other}"),
            };
            let _ = writeln!(
                out,
                "  {:50}  {:>12} {}",
                account_name,
                format_decimal(signed),
                p.currency
            );
        }
        let _ = writeln!(out);
    }

    out
}

/// Map a chart-of-accounts name to a Beancount "Expenses:Food"
/// style name. We have to invent a type prefix because
/// Beancount requires a colon-separated root.
fn beancount_account_name(name: &str) -> String {
    // Names in the chart of accounts already look like
    // "Cash on Hand" / "Accounts Receivable" — Beancount is
    // happy with spaces as long as the account name is wrapped
    // in quotes, but the syntax we emit does not quote account
    // names. We replace whitespace + dashes with safe characters
    // and prefix a synthetic root based on the account's type.
    let cleaned: String = name
        .chars()
        .map(|c| match c {
            ' ' | '\t' | '-' => '_',
            ':' => '_',
            other => other,
        })
        .collect();
    cleaned
}

fn format_beancount_date(d: NaiveDate) -> String {
    d.format("%Y-%m-%d").to_string()
}

fn format_decimal(d: rust_decimal::Decimal) -> String {
    // Beancount accepts `123.4500`; we keep the scale implied by
    // the storage type so the diff stays readable.
    let s = d.to_string();
    if s.contains('.') {
        s
    } else {
        format!("{s}.00")
    }
}

fn escape_beancount_string(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            other => out.push(other),
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn format_decimal_emits_two_dp_for_integers() {
        let n: rust_decimal::Decimal = "37".parse().unwrap();
        assert_eq!(format_decimal(n), "37.00");
    }

    #[test]
    fn format_decimal_keeps_explicit_scale() {
        let n: rust_decimal::Decimal = "37.45".parse().unwrap();
        assert_eq!(format_decimal(n), "37.45");
    }

    #[test]
    fn escape_handles_double_quote_and_backslash() {
        assert_eq!(escape_beancount_string("a\"b\\c"), "a\\\"b\\\\c");
    }

    #[test]
    fn beancount_account_name_collapses_whitespace() {
        assert_eq!(beancount_account_name("Cash on Hand"), "Cash_on_Hand");
    }
}
