//! hledger-style CSV exporter for [`LedgerSnapshot`]
//! (`d3-plaintext-export`).
//!
//! A wide row-per-transaction layout compatible with the import
//! subcommand and readable by spreadsheet tools:
//!
//! ```csv
//! date,description,payee,account1,amount1,account2,amount2
//! 2026-08-01,Coffee,Mogador,Cash on Hand,42.5000,Sales Revenue,-42.5000
//! ```
//!
//! Amounts are signed from the account's perspective: positive
//! is money into the account (DEBIT), negative is money out
//! (CREDIT). Account names are the raw chart-of-accounts names;
//! the `csv` crate quotes any cell that needs it.

use std::fmt::Write as _;

use super::LedgerSnapshot;

/// Render the snapshot as a wide hledger-style CSV document.
pub fn render(snapshot: &LedgerSnapshot) -> String {
    let mut wtr = csv::WriterBuilder::new().from_writer(Vec::new());

    let mut txns = snapshot.transactions.iter().collect::<Vec<_>>();
    txns.sort_by(|a, b| {
        a.txn_date
            .cmp(&b.txn_date)
            .then(a.created_at.cmp(&b.created_at))
    });

    let account_name: std::collections::HashMap<uuid::Uuid, String> = snapshot
        .accounts
        .iter()
        .map(|a| (a.id, a.name.clone()))
        .collect();

    // Emit a stable header; each data row is wider (one
    // account/amount pair per posting).
    let _ = wtr.write_record(["date", "description", "payee"]);

    for t in txns {
        let mut row = vec![
            t.txn_date.format("%Y-%m-%d").to_string(),
            t.description.clone(),
            t.payee.clone().unwrap_or_default(),
        ];
        for p in snapshot
            .postings
            .iter()
            .filter(|p| p.transaction_id == t.id)
        {
            let signed = match p.direction.as_str() {
                "DEBIT" => p.amount,
                "CREDIT" => -p.amount,
                other => panic!("unexpected direction {other}"),
            };
            row.push(account_name.get(&p.account_id).cloned().unwrap_or_default());
            row.push(signed.to_string());
        }
        let _ = wtr.write_record(&row);
    }

    let bytes = wtr.into_inner().expect("csv writer into inner");
    let mut out = String::with_capacity(bytes.len() + 8);
    let _ = writeln!(
        out,
        "# Generated by openaccounting {}",
        env!("CARGO_PKG_VERSION")
    );
    let _ = writeln!(
        out,
        "# Ledger: {} ({})",
        snapshot.ledger.name, snapshot.ledger.id
    );
    // `write!` is infallible on Vec<u8>; the csv writer already
    // escaped every cell, so the byte slice is valid UTF-8.
    let body = String::from_utf8(bytes).expect("csv bytes are valid UTF-8");
    out.push_str(&body);
    out
}
