//! hledger-style CSV parser for the PTA importer
//! (`d3-plaintext-export`).
//!
//! Reads the wide layout the exporter writes:
//!
//! ```csv
//! date,description,payee,account1,amount1,account2,amount2
//! ```
//!
//! Amounts are signed from the account's perspective (positive =
//! DEBIT, negative = CREDIT). Comment lines starting with `#` are
//! skipped. Rows may vary in width; fields beyond the first three
//! must come in account/amount pairs.

use chrono::NaiveDate;
use rust_decimal::Decimal;

use super::pta::{PtaPosting, PtaTxn};
use crate::domain::Direction;

/// Parse hledger-style CSV text into [`PtaTxn`]s.
pub fn parse(input: &str) -> anyhow::Result<Vec<PtaTxn>> {
    let mut rdr = csv::ReaderBuilder::new()
        .has_headers(true)
        .flexible(true)
        .comment(Some(b'#'))
        .from_reader(input.as_bytes());

    let mut txns = Vec::new();
    for (row_idx, result) in rdr.records().enumerate() {
        let record = result.map_err(|e| anyhow::anyhow!("csv row {}: {e}", row_idx + 1))?;
        if record.len() < 4 {
            anyhow::bail!(
                "csv row {}: expected at least account1,amount1 after date,description,payee",
                row_idx + 1
            );
        }
        if (record.len() - 3) % 2 != 0 {
            anyhow::bail!(
                "csv row {}: fields after payee must come in account/amount pairs",
                row_idx + 1
            );
        }

        let date = NaiveDate::parse_from_str(&record[0], "%Y-%m-%d").map_err(|_| {
            anyhow::anyhow!("csv row {}: invalid date '{}'", row_idx + 1, &record[0])
        })?;
        let description = record[1].to_string();
        let payee = if record[2].is_empty() {
            None
        } else {
            Some(record[2].to_string())
        };

        let mut postings = Vec::with_capacity((record.len() - 3) / 2);
        let mut pairs = record.iter().skip(3);
        while let (Some(account), Some(amount)) = (pairs.next(), pairs.next()) {
            let signed: Decimal = amount.parse().map_err(|_| {
                anyhow::anyhow!(
                    "csv row {}: invalid amount '{}' for account '{}'",
                    row_idx + 1,
                    amount,
                    account
                )
            })?;
            let (value, direction) = if signed > Decimal::ZERO {
                (signed, Direction::Debit)
            } else {
                (-signed, Direction::Credit)
            };
            if value.is_zero() {
                continue;
            }
            postings.push(PtaPosting {
                account_name: account.to_string(),
                amount: value,
                direction,
            });
        }

        txns.push(PtaTxn {
            date,
            description,
            payee,
            postings,
        });
    }

    Ok(txns)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parses_wide_rows() {
        let input = concat!(
            "# Generated by openaccounting 0.1.0\n",
            "date,description,payee,account1,amount1,account2,amount2\n",
            "2026-08-01,Coffee,Mogador,Cash on Hand,42.5000,Sales Revenue,-42.5000\n",
        );
        let txns = parse(input).unwrap();
        assert_eq!(txns.len(), 1);
        let t = &txns[0];
        assert_eq!(t.date.to_string(), "2026-08-01");
        assert_eq!(t.payee.as_deref(), Some("Mogador"));
        assert_eq!(t.description, "Coffee");
        assert_eq!(t.postings.len(), 2);
        assert_eq!(t.postings[0].direction, Direction::Debit);
        assert_eq!(t.postings[0].amount, Decimal::new(425000, 4));
        assert_eq!(t.postings[1].direction, Direction::Credit);
    }

    #[test]
    fn empty_payee_becomes_none() {
        let input = concat!(
            "date,description,payee,account1,amount1\n",
            "2026-08-01,Coffee,,Cash on Hand,1.00\n",
        );
        let txns = parse(input).unwrap();
        assert_eq!(txns[0].payee, None);
        assert_eq!(txns[0].postings.len(), 1);
    }

    #[test]
    fn rejects_odd_field_count() {
        let input = concat!(
            "date,description,payee,account1,amount1,account2\n",
            "2026-08-01,Coffee,Mogador,Cash on Hand,1.00,Sales Revenue\n",
        );
        assert!(parse(input).is_err());
    }

    #[test]
    fn rejects_bad_date() {
        let input = concat!(
            "date,description,payee,account1,amount1\n",
            "2026-13-01,Coffee,Mogador,Cash on Hand,1.00\n",
        );
        assert!(parse(input).is_err());
    }
}
