#!/usr/bin/env python3
"""Generate a Mermaid ER diagram from the SQL migrations.

Parses ``CREATE TABLE`` blocks (including inline ``REFERENCES``) in
``migrations/*.sql`` and emits an ``erDiagram``. The checked-in copy
at ``docs/erd.md`` is the reviewable artifact; ``--check`` fails when
the checked-in copy is stale so migration changes must regenerate it.

Accepts alternate paths so tests can run generation against fixtures.
"""

import argparse
import pathlib
import re
import sys

CREATE_TABLE = re.compile(
    r"CREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?(\w+)\s*\(",
    re.IGNORECASE,
)
# Inline foreign key: <col> <TYPE> ... REFERENCES <table>(<col>)
INLINE_REF = re.compile(r"REFERENCES\s+(\w+)\s*\(\s*(\w+)\s*\)", re.IGNORECASE)

HEADER = "<!-- Generated by scripts/generate_erd.py; do not edit by hand. -->"


def split_top_level(body: str) -> list[str]:
    parts, depth, current = [], 0, []
    for ch in body:
        if ch == "(":
            depth += 1
        elif ch == ")":
            depth -= 1
        if ch == "," and depth == 0:
            parts.append("".join(current))
            current = []
        else:
            current.append(ch)
    tail = "".join(current).strip()
    if tail:
        parts.append(tail)
    return parts


def parse_migrations(migrations_dir: pathlib.Path) -> dict[str, dict]:
    tables: dict[str, dict] = {}
    for path in sorted(migrations_dir.glob("*.sql")):
        if path.name.endswith(".down.sql"):
            continue
        text = path.read_text()
        for match in CREATE_TABLE.finditer(text):
            name = match.group(1)
            # Balance parens from the opening bracket.
            depth, idx = 0, match.end() - 1
            body_chars = []
            for idx in range(match.end() - 1, len(text)):
                ch = text[idx]
                if ch == "(":
                    depth += 1
                    if depth > 1:
                        body_chars.append(ch)
                elif ch == ")":
                    depth -= 1
                    if depth == 0:
                        break
                    body_chars.append(ch)
                else:
                    body_chars.append(ch)
            body = "".join(body_chars)
            entry = tables.setdefault(name, {"columns": [], "refs": []})
            seen = {c[0] for c in entry["columns"]}
            for part in split_top_level(body):
                part = part.strip()
                head = part.split()
                if not head:
                    continue
                first = head[0].strip('"').upper()
                if first in ("PRIMARY", "FOREIGN", "UNIQUE", "CHECK", "CONSTRAINT"):
                    continue
                col = head[0].strip('"')
                col_type = head[1].upper() if len(head) > 1 else ""
                col_type = re.split(r"\W", col_type)[0]
                ref = INLINE_REF.search(part)
                if col not in seen:
                    entry["columns"].append((col, col_type))
                    seen.add(col)
                if ref:
                    rel = (col, ref.group(1))
                    if rel not in entry["refs"]:
                        entry["refs"].append(rel)
    return tables


def render(tables: dict[str, dict]) -> str:
    lines = [HEADER, "# Data-model ERD", "",
             "Generated from `migrations/*.sql`. Regenerate with",
             "`python3 scripts/generate_erd.py` after any migration change.", "",
             "```mermaid", "erDiagram"]
    for table in sorted(tables):
        lines.append(f"    {table} {{")
        for col, col_type in tables[table]["columns"]:
            lines.append(f"        {col_type or 'TEXT'} {col}")
        lines.append("    }")
    for table in sorted(tables):
        for col, target in tables[table]["refs"]:
            if target in tables:
                lines.append(f"    {table} }}|--|| {target} : \"{col}\"")
    lines.extend(["```", ""])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--migrations-dir", default="migrations")
    parser.add_argument("--output", default="docs/erd.md")
    parser.add_argument("--check", action="store_true",
                        help="Fail if the checked-in diagram differs "
                             "from freshly generated output")
    args = parser.parse_args()

    root = pathlib.Path(__file__).resolve().parent.parent
    migrations_dir = pathlib.Path(args.migrations_dir)
    if not migrations_dir.is_absolute():
        migrations_dir = root / migrations_dir
    output = pathlib.Path(args.output)
    if not output.is_absolute():
        output = root / output

    fresh = render(parse_migrations(migrations_dir))
    if args.check:
        try:
            checked_in = output.read_text()
        except OSError:
            print(f"FAIL: checked-in diagram missing: {output}")
            return 1
        if checked_in != fresh:
            print(f"FAIL: {output} is stale; run "
                  "`python3 scripts/generate_erd.py` to regenerate")
            return 1
        print(f"OK: {output} matches migrations")
        return 0

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(fresh)
    tables = parse_migrations(migrations_dir)
    print(f"Wrote {output} ({len(tables)} tables)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
