//! Per-test database and HTTP server fixture.
//!
//! This module is gated behind the `test-support` Cargo feature
//! (and on `#[cfg(test)]`) so it never ships in a production
//! binary. It mirrors the pattern used in
//! `/home/paul/code/openpanel/crates/openpanel-test-support/`:
//! each test gets its own fresh PostgreSQL database and its own
//! real axum server on a random local port, torn down on `Drop`.
//!
//! Two entry points:
//!
//! - [`TestDb`] — RAII wrapper around a per-test PostgreSQL
//!   database. Created with a unique `oa_test_<uuid>` name so two
//!   tests never share state. `Drop` drops the database.
//!
//! - [`TestServer`] — boots the real `axum::Router` from
//!   [`crate::build_router`] against a fresh `TestDb`, on a
//!   random local port. Exposes a `reqwest::Client` with cookie
//!   support and a `bootstrap_user` helper that registers, logs
//!   in, and returns the captured session cookie.
//!
//! Both require `DATABASE_URL` to point at a reachable
//! PostgreSQL with a user that has `CREATEDB` privilege.

#![allow(clippy::expect_used, clippy::unwrap_used, clippy::panic)]

use std::env;
use std::path::PathBuf;
use std::sync::Arc;

use sqlx::postgres::{PgConnectOptions, PgPoolOptions};
use sqlx::PgPool;
use tempfile::TempDir;
use tokio::net::TcpListener;
use tokio::task::JoinHandle;
use uuid::Uuid;

use crate::storage::FilesystemStore;
use crate::{build_router, AppConfig, AppState};

/// A per-test PostgreSQL database.
///
/// The database name is `oa_test_<uuid>`; the URL is built by
/// swapping the database segment of `DATABASE_URL` with the test
/// name. The admin URL (used to issue `CREATE DATABASE` and
/// `DROP DATABASE`) is the same URL with the database swapped
/// for `postgres`.
pub struct TestDb {
    admin_url: String,
    test_db_name: String,
    pool: PgPool,
}

impl TestDb {
    /// Create a fresh test database, run all migrations, return
    /// the connection pool.
    ///
    /// # Panics
    /// Panics if `DATABASE_URL` is unset or the connection /
    /// migration fails. Both are programmer errors, not test
    /// logic.
    pub async fn new() -> Self {
        let source_url =
            env::var("DATABASE_URL").expect("DATABASE_URL must be set for tests; see .env.test");
        let admin_url = swap_database(&source_url, "postgres");
        let test_db_name = format!("oa_test_{}", Uuid::new_v4().simple());
        let test_url = swap_database(&source_url, &test_db_name);

        // 1. Connect to the admin DB and create the test DB.
        {
            let admin_opts: PgConnectOptions = admin_url.parse().expect("parse admin DATABASE_URL");
            let admin_pool = PgPoolOptions::new()
                .max_connections(1)
                .connect_with(admin_opts)
                .await
                .expect("connect admin DATABASE_URL");
            // CREATE DATABASE cannot be parameterised; the name is
            // generated by us (UUID, no user input), so the
            // format! is safe.
            let create_stmt = format!("CREATE DATABASE \"{test_db_name}\"");
            sqlx::query(&create_stmt)
                .execute(&admin_pool)
                .await
                .expect("CREATE DATABASE");
            admin_pool.close().await;
        }

        // 2. Connect to the new test DB and run migrations.
        let test_opts: PgConnectOptions = test_url.parse().expect("parse test DATABASE_URL");
        let pool = PgPoolOptions::new()
            .max_connections(4)
            .connect_with(test_opts)
            .await
            .expect("connect test DATABASE_URL");
        sqlx::migrate!("./migrations")
            .run(&pool)
            .await
            .expect("run migrations on test DB");

        // 3. The session store has its own table; install it now so
        //    the axum server can use it.
        let session_store = tower_sessions_sqlx_store::PostgresStore::new(pool.clone());
        session_store
            .migrate()
            .await
            .expect("session store migrate");

        Self {
            admin_url,
            test_db_name,
            pool,
        }
    }

    /// The connection pool for the test database.
    pub fn pool(&self) -> PgPool {
        self.pool.clone()
    }

    /// The unique name of the test database (`oa_test_<uuid>`).
    pub fn name(&self) -> &str {
        &self.test_db_name
    }
}

impl Drop for TestDb {
    fn drop(&mut self) {
        // Drop is sync, the async runtime may already be torn
        // down. Use the synchronous `postgres` crate on a fresh
        // thread to issue DROP DATABASE WITH (FORCE) so it works
        // even if the test DB has lingering connections from the
        // pool we just closed.
        let admin_url = self.admin_url.clone();
        let name = self.test_db_name.clone();
        let _ = std::thread::Builder::new()
            .name("oa-test-db-drop".into())
            .spawn(move || {
                let Ok(mut client) = postgres::Client::connect(&admin_url, postgres::NoTls) else {
                    // Nothing useful we can do; the next test will
                    // get a fresh DB and the leak is bounded by
                    // Postgres' own cleanup.
                    return;
                };
                // FORCE terminates any remaining backends
                // connected to the test DB before dropping it.
                let stmt = format!("DROP DATABASE IF EXISTS \"{name}\" WITH (FORCE)");
                let _ = client.batch_execute(&stmt);
            })
            .map(|h| h.join());
    }
}

/// Per-test axum server backed by a fresh `TestDb`.
pub struct TestServer {
    base_url: String,
    client: reqwest::Client,
    db: TestDb,
    _sandbox: Arc<TempDir>,
    _handle: JoinHandle<()>,
}

impl TestServer {
    /// Boot a real axum server backed by a fresh `TestDb` with
    /// the placeholder-SHA-256 gate off (lenient mode). The
    /// existing tests rely on the lenient mode.
    pub async fn new() -> Self {
        Self::new_with_secret(
            "test-secret-do-not-use-in-production-please-replace-with-64-random-chars",
        )
        .await
    }

    /// Boot a real axum server with a caller-supplied session
    /// secret. The secret MUST be at least 32 characters; this
    /// matches the production invariant.
    pub async fn new_with_secret(secret: &str) -> Self {
        if secret.len() < 32 {
            panic!("TestServer secret must be at least 32 characters");
        }
        let db = TestDb::new().await;
        let sandbox = Arc::new(
            tempfile::Builder::new()
                .prefix("oa-test-")
                .tempdir()
                .expect("tempdir"),
        );
        let documents_dir: PathBuf = sandbox.path().join("documents");
        let storage = FilesystemStore::new(&documents_dir)
            .await
            .expect("create FilesystemStore in sandbox");

        let state = AppState {
            pool: db.pool(),
            storage,
        };
        let config = AppConfig::new(secret.to_string()).expect("valid app config");
        let app = build_router(state, config);

        let listener = TcpListener::bind("127.0.0.1:0")
            .await
            .expect("bind 127.0.0.1:0");
        let addr = listener.local_addr().expect("local addr");
        let base_url = format!("http://{addr}");

        let handle = tokio::spawn(async move {
            let _ = axum::serve(
                listener,
                app.into_make_service_with_connect_info::<std::net::SocketAddr>(),
            )
            .await;
        });

        let client = reqwest::Client::builder()
            .cookie_store(true)
            .redirect(reqwest::redirect::Policy::none())
            .build()
            .expect("build reqwest client");

        Self {
            base_url,
            client,
            db,
            _sandbox: sandbox,
            _handle: handle,
        }
    }

    /// The base URL, e.g. `http://127.0.0.1:54321`.
    pub fn base_url(&self) -> &str {
        &self.base_url
    }

    /// A preconfigured `reqwest::Client`. The client keeps its
    /// own cookie jar, so logging in once keeps subsequent
    /// requests in the same test authenticated.
    pub fn client(&self) -> &reqwest::Client {
        &self.client
    }

    /// The per-test database handle.
    pub fn db(&self) -> &TestDb {
        &self.db
    }

    /// Convenience: register a user, log them in, return the
    /// `Set-Cookie` value the server sent. Tests that want to
    /// drive the auth flow themselves can use the lower-level
    /// `client()` API and ignore the return value of this method.
    pub async fn bootstrap_user(&self, username: &str, email: &str, password: &str) -> String {
        // Register
        let resp = self
            .client
            .post(format!("{}/register", self.base_url))
            .form(&[
                ("email", email),
                ("username", username),
                ("password", password),
                ("password_confirm", password),
            ])
            .send()
            .await
            .expect("register request");
        // 303 See Other → /login?next=...
        let status = resp.status();
        if !status.is_success() && status.as_u16() != 303 {
            let body = resp.text().await.unwrap_or_default();
            panic!("register failed: {status} body={body}");
        }

        // Login
        let resp = self
            .client
            .post(format!("{}/login", self.base_url))
            .form(&[
                ("email", email),
                ("password", password),
                ("next", "/ledgers"),
            ])
            .send()
            .await
            .expect("login request");
        let status = resp.status();
        if !status.is_success() && status.as_u16() != 303 {
            let body = resp.text().await.unwrap_or_default();
            panic!("login failed: {status} body={body}");
        }

        // Extract the Set-Cookie header for oa_session. Use
        // the response cookies (the client jar already has
        // it) or the raw header — reqwest with cookie_store
        // keeps them internally.
        resp.headers()
            .get_all(reqwest::header::SET_COOKIE)
            .iter()
            .filter_map(|v| v.to_str().ok())
            .find_map(|s| {
                let cookie = s.split(';').next().unwrap_or("");
                if cookie.starts_with("oa_session=") {
                    Some(cookie.to_string())
                } else {
                    None
                }
            })
            .expect("oa_session cookie set on login response")
    }
}

impl Drop for TestServer {
    fn drop(&mut self) {
        self._handle.abort();
        // `_db` is dropped after this struct, so its Drop fires
        // and removes the per-test DB.
    }
}

/// Swap the database segment of a Postgres URL.
///
/// `postgres://u:p@h:port/db?args` → `postgres://u:p@h:port/<new_db>?args`.
/// If the URL has no path, the new database is appended.
fn swap_database(url: &str, new_db: &str) -> String {
    // Split on '/' once after the scheme.
    let (scheme_and_auth, after_db) = match url.split_once("://") {
        Some(parts) => parts,
        None => panic!("DATABASE_URL is missing scheme: {url}"),
    };
    let (host_port, query) = match after_db.split_once('?') {
        Some((hp, q)) => (hp, format!("?{q}")),
        None => (after_db, String::new()),
    };
    let (host, _old_db) = match host_port.split_once('/') {
        Some(parts) => parts,
        None => panic!("DATABASE_URL is missing database name: {url}"),
    };
    format!("{scheme_and_auth}://{host}/{new_db}{query}")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn swap_database_replaces_path_segment() {
        assert_eq!(
            swap_database("postgres://u:p@h:5432/d", "postgres"),
            "postgres://u:p@h:5432/postgres"
        );
        assert_eq!(
            swap_database("postgres://u:p@h:5432/d?sslmode=disable", "x"),
            "postgres://u:p@h:5432/x?sslmode=disable"
        );
        assert_eq!(swap_database("postgres://h/d", "x"), "postgres://h/x");
    }

    #[tokio::test]
    async fn testdb_creates_unique_db_names() {
        let a = TestDb::new().await;
        let b = TestDb::new().await;
        assert_ne!(a.name(), b.name());
        // Both DBs are queryable.
        let pool = a.pool();
        let n: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM ledgers")
            .fetch_one(&pool)
            .await
            .unwrap();
        assert_eq!(n.0, 0);
    }

    #[tokio::test]
    async fn testdb_runs_all_migrations() {
        let db = TestDb::new().await;
        let pool = db.pool();
        // _sqlx_migrations is the table sqlx::migrate! writes.
        let n: (i64,) =
            sqlx::query_as("SELECT COUNT(*) FROM _sqlx_migrations WHERE success = TRUE")
                .fetch_one(&pool)
                .await
                .unwrap();
        assert!(n.0 >= 18, "expected at least 18 migrations, got {}", n.0);
    }
}
